### ISSUE TITLE
Can't edit the powerApp

### ISSUE THREAD

**Issue by kroothkrabbes** [SYCOR-Group/Back2Work#1]
It's not possible to edit the powerApp therfore the dataconnection can not be changed.
It might be a version conflict as the actual app version when i create an app is 20023.8 your version is 20051.16

br
karsten
![image](https://user-images.githubusercontent.com/34656227/82240230-59162d80-993a-11ea-89e9-eecab0445bf7.png)

**Comment by HardenTor** [comment]
Yes, the application can only be edited in PowerApps Version 20051.16 and later. Unfortunately there is no possibility to export a PowerApp Solution in an older version than the current version of the development tenant. In general it will take some days until all environments are on the latest version. However, it could be one possibility to generate an new environment, this would get the latest version available in the desired region.
