### ISSUE TITLE
Flow run failed

### ISSUE THREAD

**Issue by ManfredBr** [SYCOR-Group/Back2Work#3]
Hello team,

**DeployB2WSPLists** fails  at step "Create Site List" with error message **"BadGateway"**. Resubmitted the flow a few times, every time it fails at the same step.
On Sharepoint Site I can see all lists (surprising) but I guess something is missing.

Any help is very appreciated.
Thanks,   Manfred

**Comment by HardenTor** [comment]
Hi Manfred,
when searching on Google for this issue (https://www.google.de/search?q=create+sharepoint+list+bad+gateway), you will find that this response may have different reasons. It is hard to analyze the base reason in your environment. Just some hints for you:
- When the Admin App and the User App are running without any errors, your data model will complete and nothing is missing.
- The flow can only be run once for a site - the flow will throw errors when objects already exists on the site. So, before resubmitting and running the flow you should also generate a new site.
- Ensure that the site and site collection are using an English default teamsite template. Ensure that no additional site collection features are activated (e.g. publishing feature).

I hope this helps
Torsten

**Comment by HardenTor** [comment]
No further feedback should work now:-)
